theme: jekyll-theme-minimal
title: EE 021 Hall of Fame
description: This is a Repository for past and future midterm/final projects for EE 021 - Introduction fo Electrical Engineering Programming at UC Merced.